modLoader="javafml"
loaderVersion="[37,)"
license="MIT License"
issueTrackerURL="https://github.com/EwyBoy/Template-Mod/issues"

[[mods]]
modId="template"
version="${file.jarVersion}"
displayName="Template"
displayURL="https://www.curseforge.com/minecraft/mc-mods/Mod-Name"
credits=""
authors="Ewy"
description=""

[[dependencies.template]]
modId="forge"
mandatory=true
versionRange="[37,)"
ordering="NONE"
side="BOTH"

[[dependencies.template]]
modId="minecraft"
mandatory=true
versionRange="[1.17.1, 1.18)"
ordering="NONE"
side="BOTH"