modLoader="javafml"
loaderVersion="[37,)"
license="MIT License"
issueTrackerURL="https://github.com/EwyBoy/Template-Mod/issues"

[[mods]]
modId="enderpay"
version="${file.jarVersion}"
displayName="Ender Pay"
displayURL="https://www.curseforge.com/minecraft/mc-mods/Ender-Pay"
credits=""
authors="Ewy"
description=""

[[dependencies.enderpay]]
modId="forge"
mandatory=true
versionRange="[37,)"
ordering="NONE"
side="BOTH"

[[dependencies.enderpay]]
modId="minecraft"
mandatory=true
versionRange="[1.17.1, 1.18)"
ordering="NONE"
side="BOTH"